language: php
php:
  - "5.3"
  - "5.4"
  - "5.5"

before_script:
  - pear config-show
  - pear channel-discover pear.bovigo.org
  - pear install bovigo/vfsStream-beta

script: phpunit tests

notifications:
  email: false
  irc: false
