language: php
php:
  - "5.3"
  - "5.4"
  - "5.5"

before_script:
  - pear channel-discover pear.bovigo.org
  - pear install bovigo/vfsStream-beta
  - find / -name vfsStream.php

script: phpunit tests

notifications:
  email: false
  irc: false
