language: php
php:
  - "5.3"
  - "5.4"
  - "5.5"

before_script:
  - pear channel-discover pear.bovigo.org
  - pear install bovigo/vfsStream-beta
  - ls /home/travis/.phpenv/versions/5.4.45/share/pear
  - ls /home/travis/.phpenv/versions/5.3.29/share/pear
  - ls /home/travis/.phpenv/versions/5.5.38/share/pear
  - ls /home/travis/.phpenv/versions

script: phpunit tests

notifications:
  email: false
  irc: false
